sudo: false
language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: mvn --batch-mode --fail-at-end install 2>&1 